global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    static_configs:
      - targets: ['host.docker.internal:8080'] # points to your local Spring Boot app

    basic_auth:
      username: 'admin'
      password: 'admin123'
