spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hibernate
    username: root
    password: Asilbek_2005
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

data:
  trainers:
    path: data/trainers.json
  trainees:
    path: data/trainees.json
  trainings:
    path: data/trainings.json
